# Generated by Django 4.2.4 on 2023-08-19 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Сurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_code', models.CharField(max_length=3, verbose_name='Код')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
            ],
            options={
                'verbose_name_plural': 'Валюты',
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата сбора данных')),
                ('value', models.DecimalField(decimal_places=4, max_digits=7, verbose_name='Значение')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='currencies.сurrency', verbose_name='Валюта')),
            ],
            options={
                'verbose_name_plural': 'Курсы валют',
                'unique_together': {('date', 'currency')},
            },
        ),
    ]
